### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by stefanoskj** [parasite85/tuya_tygwzw1_hack#1]
following your guide, when I try to compile the project I get this error:
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-objcopy: 1: Syntax error: "(" unexpected
make[1]: *** [application.mk:779: prerequirement] Error 2
make[1]: Leaving directory '/home/stefano/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
make: *** [Makefile:17: ram_all] Error 2

Can you help me, please?

thanks

**Comment by parasite85** [comment]
Hello,
Stefano, can you share some more details ?
I have been building it on Ubuntu 23.10.
I see no such error. Can you attach full compilation log ?
It seems also application.mk:779 differs from original can you attach diff ?

**Comment by stefanoskj** [comment]
hello again,
this is the full log
stefano@stefano-desktop:~/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE$ make
if [ ! -d ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ] ; then tar -jxf ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2 -C ../../../tools/arm-none-eabi-gcc/ ; mv ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3 ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ; fi
make[1]: Entering directory '/home/stefano/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
===========================================================
Build application
===========================================================
mkdir -p application/Debug/obj
mkdir -p application/Debug/bin
cp ../../../component/soc/realtek/8195a/misc/bsp/image/ram_1.r.bin application/Debug/obj/ram_1.r.bin
chmod 777 application/Debug/obj/ram_1.r.bin
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-objcopy --rename-section .data=.loader.data,contents,alloc,load,readonly,data -I binary -O elf32-littlearm -B arm application/Debug/obj/ram_1.r.bin application/Debug/obj/ram_1.r.o 
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-objcopy: 1: Syntax error: "(" unexpected
make[1]: *** [application.mk:779: prerequirement] Error 2
make[1]: Leaving directory '/home/stefano/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
make: *** [Makefile:17: ram_all] Error 2

currently I am trying with ubuntu 23.10 as you suggest, before I was trying with raspbian. Both of them on raspberry pi 4.
I am following exactly your guide, without change any files. Let me know if you have any suggestions. thank you

**Comment by parasite85** [comment]
Hi,
Regarding your problem
> currently I am trying with ubuntu 23.10 as you suggest, before I was trying with raspbian. Both of them on raspberry pi 4.
I am following exactly your guide, without change any files. Let me know if you have any suggestions. thank you

Well, maybe i have not mentioned about it but it was built on x86 architecture.
Realtek has added GCC arm toolchain **binaries** for 32 bit x86 arch.

It can be easilty checked
`rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE$ file ../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-objcopy`
gives
`
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-objcopy: ELF 32-bit LSB executable, Intel 80386, version 1 (SYSV), dynamically linked, interpreter /lib/ld-linux.so.2, for GNU/Linux 2.6.8, stripped
`

You have two options
- Download toolchain binaries for your architecture from ARM website (https://developer.arm.com/downloads/-/arm-gnu-toolchain-downloads) but **WARNING**: Realtek SDK is using very old toolchain (old gcc). I have tried to use new version but got some compile warnings. Have no time and will to get rid of them. **NOTE:** I`m not sure if flashing part will work on ARM architecture. SDK uses some binaries for it. I have not investigated it.
- Use x86 PC to build it. Try with your normal distro to build. You can always set up a Virtual Machine or use Docker env to build it.

I strongly suggest to use x86 PC for it

**Comment by parasite85** [comment]
Great progress,
Well, it seems that flash procedure is done correctly. Not sure what is going on, but we will figure it out.
Unfortunately, I cannot check right now, but ensure that you are using correct baudrate (I think it should be 38400)

If baudrate is ok, then try this (temporary) solution first:
- attach debugger to your HW
- start run_openocd.sh
- In `rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE` directory run `make ramdebug` . This will load your sofrware to ram memory and start it. It should work (of course temporary). If it will work, we will inspect the rest of stuff.

At least you can temporarily start everthing up.

Regarding not booting after flash - there might be two issues. 
- For flash, there is small image manipulation done. It might be done wrongly. When you start from ram (using ramdebug) then image is written without any additional manipulations.
- USB UART adatper issue. I have seen it at my side. I do not know why, but with ramdebug everything was fine and if i flashed firmware, i have no data from UART on incompatible UART.  If you have some logic analyzer like Saleae (you can buy cheap one on Chinese market) then you can easily check if some data is being transmitted. Y

**HINT**: I have observed that on incompatible (broken) UART I do not see any "early boot" prints like:
```
=========================================================

ROM Version: 0.3

Build ToolChain Version: gcc version 4.8.3 (Realtek ASDK-4.8.3p1 Build 2003) 

=========================================================
Check boot type form eFuse
SPI Initial
Image1 length: 0x41fc, Image Addr: 0x10000bc8
Image1 Validate OK, Going jump to Image1

BOOT from Flash:YES
```

I had no time to debug it.
Anyway, please contribute to repo if you have something to fix.

**Comment by parasite85** [comment]
Any news ? Do you need still help ?

**Comment by stefanoskj** [comment]
I am still struggling. I found the right usb to send me data during boot. I had a mistake error on memory 2. I supposed I compiled in the wrong way. So I decide to install Cygwin on windows. I managed to compile, but now I have some issues to flash because openocd is not correct install. I am studiyng to find a solution. I let you know if I win the battle.

**Comment by Stasiz** [comment]
> **HINT**: I have observed that on incompatible (broken) UART I do not see any "early boot" prints (these prints came from ROM, they will always be printed, no matter what is in flash) like:

What adapter are you using? Does it have auto speed negotiation? I have a UART adapter with a CP2102 chipset. Boot log has a baud rate of 38400 and after booting is 115200. And I have to change it manually.

**Comment by stefanoskj** [comment]
At the end I disassembled the zigbee module from the board and I am using it connected directly through an UART usb. It is worrking pretty well. Thank you again for your support

**Comment by parasite85** [comment]
@stefanoskj: Great news. At least something is working.

To be honest i do not really remember now which one i have been using. I have couple of them and now i have disassembled everything. If it will be really needed, I`ll try to check which one was working.
For sure it was without any "speed negotiation" (at least from UART PoV,) it tries to adopt speed)..

**Comment by parasite85** [comment]
@stefanoskj: if you have something to share/add to repo, please do it.
Can we close this issue ?

**Comment by stefanoskj** [comment]
Yes, you can close the ticket. Thank you again

**Comment by Mantikor** [comment]
@parasite85 please, stop closing this thread) I have some troubles with RTL fw flashing. Try to use: Windows WSL Debian, Cygwin, Live distro of Ubuntu 23.04.

**_run openOCD - ok:_**
`PS C:\WORK\diy\tuya\rtl_firmware\project\realtek_ameba1_va0_example\GCC-RELEASE> .\run_openocd.bat

C:\WORK\diy\tuya\rtl_firmware\project\realtek_ameba1_va0_example\GCC-RELEASE>taskkill /F /IM openocd.exe
ERROR: The process "openocd.exe" not found.

C:\WORK\diy\tuya\rtl_firmware\project\realtek_ameba1_va0_example\GCC-RELEASE>C:\WORK\diy\tuya\OpenOCD\bin\openocd.exe -f interface\stlink.cfg -f ..\..\..\component\soc\realtek\8195a\misc\gcc_utility\openocd\ameba1.cfg
Open On-Chip Debugger 0.12.0 (2023-10-02) [https://github.com/sysprogs/openocd]
Licensed under GNU GPL v2
libusb1 09e75e98b4d9ea7909e8837b7a3f00dda4589dc3
For bug reports, read
        http://openocd.org/doc/doxygen/bugs.html
Info : auto-selecting first available session transport "hla_swd". To override use 'transport select <transport>'.
Info : The selected transport took over low-level target control. The results might differ compared to plain JTAG/SWD
DEPRECATED! use 'adapter speed' not 'adapter_khz'
DEPRECATED! use 'adapter srst delay' not 'adapter_nsrst_delay'
DEPRECATED! use 'adapter srst delay' not 'adapter_nsrst_delay'
ameba1_init
Info : Listening on port 6666 for tcl connections
Info : Listening on port 4444 for telnet connections
Info : clock speed 500 kHz
Info : STLINK V2J39S7 (API v2) VID:PID 0483:3748
Info : Target voltage: 3.229377
Info : [rtl8195a.cpu] Cortex-M3 r2p1 processor detected
Info : [rtl8195a.cpu] target has 6 breakpoints, 4 watchpoints
Info : starting gdb server for rtl8195a.cpu on 3333
Info : Listening on port 3333 for gdb connections`

**_Cygwin:_**
`Admin@HP-ProDesk400G6 ~/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE
$ make ramdebug
if [ ! -f ../../../tools/arm-none-eabi-gcc/4_8-2014q3.tar ] ; then cat ../../../tools/arm-none-eabi-gcc/4_8-2014q3.tar* > ../../../tools/arm-none-eabi-gcc/4_8-2014q3.tar; fi;\
if [ ! -d ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ] ; then tar -xf ../../../tools/arm-none-eabi-gcc/4_8-2014q3.tar -C ../../../tools/arm-none-eabi-gcc/ ; fi
make[1]: Entering directory '/home/Admin/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
../../../component/soc/realtek/8195a/misc/gcc_utility//Check_Jtag.sh
../../../component/soc/realtek/8195a/misc/gcc_utility//Check_Jtag.sh: line 2: $'\r': command not found
../../../component/soc/realtek/8195a/misc/gcc_utility//Check_Jtag.sh: line 6: $'\r': command not found
0
0
../../../component/soc/realtek/8195a/misc/gcc_utility//Check_Jtag.sh: line 12: $'\r': command not found
/home/Admin/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE
../../../component/soc/realtek/8195a/misc/gcc_utility//Check_Jtag.sh: line 14: $'\r': command not found
../../../component/soc/realtek/8195a/misc/gcc_utility//Check_Jtag.sh: line 78: syntax error: unexpected end of file
make[1]: *** [application.mk:855: ramdebug] Error 2
make[1]: Leaving directory '/home/Admin/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
make: *** [Makefile:38: ramdebug] Error 2`

**_Debian WSL:_**
`root@HP-ProDesk400G6:/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE# make ramdebug
if [ ! -d ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ] ; then tar -jxf ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2 -C ../../../tools/arm-none-eabi-gcc/ ; mv ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3 ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ; fi
make[1]: Entering directory '/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-gdb -x ../../../component/soc/realtek/8195a/misc/gcc_utility//rtl_gdb_ramdebug.txt
bash: line 1: ../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-gdb: No such file or directory
make[1]: *** [application.mk:855: ramdebug] Error 127
make[1]: Leaving directory '/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
make: *** [Makefile:38: ramdebug] Error 2
root@HP-ProDesk400G6:/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE#`

Ubuntu Live:
![photo_2024-02-25_17-19-59_2](https://github.com/parasite85/tuya_tygwzw1_hack/assets/17388366/3d83ca1e-e951-4732-ab40-74aaeaea2ac0)

**Comment by Stasiz** [comment]
@Mantikor 
You need **Install all required files for i386 running i386 programs**. 
Or just install the latest version of Debian. Do it `sudo apt install libc6-dev-i386 gawk` and that should be enough.
Everything compiles fine but is flashed to the wrong addresses. :cry:

**Comment by Mantikor** [comment]
@Stasiz I have installed (libc6-dev-i386 gawk) on Debian WSL, but nothing changed...
`root@HP-ProDesk400G6:/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE# make ramdebug
if [ ! -d ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ] ; then tar -jxf ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2 -C ../../../tools/arm-none-eabi-gcc/ ; mv ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3 ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ; fi
make[1]: Entering directory '/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-gdb -x ../../../component/soc/realtek/8195a/misc/gcc_utility//rtl_gdb_ramdebug.txt
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-gdb: error while loading shared libraries: libncurses.so.5: cannot open shared object file: No such file or directory
make[1]: *** [application.mk:855: ramdebug] Error 127
make[1]: Leaving directory '/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
make: *** [Makefile:38: ramdebug] Error 2
root@HP-ProDesk400G6:/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE#`

**Comment by Stasiz** [comment]
@Mantikor 
> I have installed (libc6-dev-i386 gawk) on Debian WSL, but nothing changed... `error while loading shared libraries: libncurses.so.5`

I mean pure Debian.
With WSL, Ubuntu, linuxmint and etc. you will continue to complete the quest. Try install  lib32ncurses5-dev or libncurses5:i386

**Comment by Mantikor** [comment]
@Stasiz thank you so much! I didn't see libncurses5 error... But after your suggestion, i have sent a few commands:

`dpkg --add-architecture i386 && apt update`

and after:

`apt install libncurses5:i386`

and got result on my Debian WSL (Windows WSL not so bad :) ):

`root@HP-ProDesk400G6:/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE# make ramdebug
if [ ! -d ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ] ; then tar -jxf ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3-20140805-linux.tar.bz2 -C ../../../tools/arm-none-eabi-gcc/ ; mv ../../../tools/arm-none-eabi-gcc/gcc-arm-none-eabi-4_8-2014q3 ../../../tools/arm-none-eabi-gcc/4_8-2014q3 ; fi
make[1]: Entering directory '/mnt/c/WORK/diy/rtl_firmware/project/realtek_ameba1_va0_example/GCC-RELEASE'
../../../tools/arm-none-eabi-gcc/4_8-2014q3/bin//arm-none-eabi-gdb -x ../../../component/soc/realtek/8195a/misc/gcc_utility//rtl_gdb_ramdebug.txt
GNU gdb (GNU Tools for ARM Embedded Processors) 7.6.0.20140731-cvs
Copyright (C) 2013 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "--host=i686-linux-gnu --target=arm-none-eabi".
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
../../../component/soc/realtek/8195a/misc/gcc_utility//rtl_gdb_ramdebug.txt:6: Error in sourced command file:
:2331: Connection timed out.`

will try with connected device. @Stasiz did you try to dump backup from RTL MCU? I had dumped 512K from RTL, but I'm not sure I downloaded the correct dump...
[rtl_gdb_flash_read.gdb.txt](https://github.com/parasite85/tuya_tygwzw1_hack/files/14397485/rtl_gdb_flash_read.gdb.txt)

**Comment by Mantikor** [comment]
Hey! Jedy return) I have used Ubuntu 23.10 Live. And install all needed i386 libs, compile and flash image to main cpu, but after start I see the next:
![Screenshot 2024-02-26 221305](https://github.com/parasite85/tuya_tygwzw1_hack/assets/17388366/6c3d484d-def8-42ae-a781-a21561760342)
or next:
![Screenshot 2024-02-26 224746](https://github.com/parasite85/tuya_tygwzw1_hack/assets/17388366/c630a262-69a9-4a8e-bd46-17ed2241a1fd)
so... my power for today is go down(((

**Comment by Mantikor** [comment]
@Stasiz @parasite85 any recommendations? I think not whole firmware was written into mcu?

**Comment by Mantikor** [comment]
Next episode) Today I have tried `make ramdebug` instead `make flash`. And it works!!! MCU was loaded with sw, I can listed the SSID's, and also connect to my home WiFi. I got ip address and try to connect zigbee2mqtt to device, but I had an error.
configuration.yaml
```
homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://my-mqtt-server-ip:1883'
  user: mqtt-user
  password: mqtt-password
serial:
  adapter: ezsp
  baudrate: 115200
  port: tcp://my-ex-tuya-ip:80
  rtscts: false

```
error:
```
Zigbee2MQTT:info  2024-02-28 23:47:15: Logging to console and directory: '/app/data/log/2024-02-28.23-47-15' filename: log.txt
Zigbee2MQTT:info  2024-02-28 23:47:16: Starting Zigbee2MQTT version 1.35.3 (commit #fe0742a)
Zigbee2MQTT:info  2024-02-28 23:47:16: Starting zigbee-herdsman (0.33.8)
Zigbee2MQTT:error 2024-02-28 23:47:25: Error while starting zigbee-herdsman
Zigbee2MQTT:error 2024-02-28 23:47:25: Failed to start zigbee
Zigbee2MQTT:error 2024-02-28 23:47:25: Check https://www.zigbee2mqtt.io/guide/installation/20_zigbee2mqtt-fails-to-start.html for possible solutions
Zigbee2MQTT:error 2024-02-28 23:47:25: Exiting...
Zigbee2MQTT:error 2024-02-28 23:47:25: Error: Failure send exportKey:{"type":"Buffer","data":[29,0,1,20,1,3,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0]}
    at /app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/ezsp.ts:646:23
    at Queue.execute (/app/node_modules/zigbee-herdsman/src/utils/queue.ts:35:20)
    at Driver.getKey (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:866:29)
    at Driver.startup (/app/node_modules/zigbee-herdsman/src/adapter/ezsp/driver/driver.ts:246:27)
    at Controller.start (/app/node_modules/zigbee-herdsman/src/controller/controller.ts:132:29)
    at Zigbee.start (/app/lib/zigbee.ts:60:27)
    at Controller.start (/app/lib/controller.ts:109:27)
    at start (/app/index.js:107:5)
```
 And @parasite85 I need your help with flash instead ramdebug :)

**Comment by Mantikor** [comment]
Finally I have reflashed ZigBee module with your (@parasite85) binary instead compiled by me via Simplicity Studio, and start rtl mcu with ramdebug:
![Screenshot 2024-02-29 121933](https://github.com/parasite85/tuya_tygwzw1_hack/assets/17388366/ed07af94-c172-429a-9c2c-8a13b8b24b09)
and all components works, zigbee2mqtt successfully connected to device via WiFi (tested on few ZigBee power sockets). And last step what I see: fix flash script for flash non-modified binary to the rtl mcu.

**Comment by Stasiz** [comment]
@Mantikor 
> @Stasiz did you try to dump backup from RTL MCU? I had dumped 512K from RTL, but I'm not sure I downloaded the correct dump... [rtl_gdb_flash_read.gdb.txt](https://github.com/parasite85/tuya_tygwzw1_hack/files/14397485/rtl_gdb_flash_read.gdb.txt)

Wow you have achieved a lot.
You cut rtl_gdb_flash_write.gdb.txt? I tried it but it doesn't look like a valid dump.

**Comment by Mantikor** [comment]
Now I got only this log after flash:
```
==========================================================
Flash Downloader Build Time: # 2017/10/25-10:51:37
==========================================================
OTA offset : 00006000
EraseMode : 2
FirmwareSize : 424420
Skip system data
Skip calibration
Flash erace done
Flash download start
Flash download done
=========================================================

ROM Version: 0.3

Build ToolChain Version: gcc version 4.8.3 (Realtek ASDK-4.8.3p1 Build 2003)

=========================================================
Check boot type form eFuse
SPI Initial
Image1 length: 0x41fc, Image Addr: 0x10000bc8
Image1 Validate OK, Going jump to Image1

BOOT from Flash:YES
SPI calibration
Find the avaiable window
Baud:3; auto_length:0; Delay start:0; Delay end:63
[SPIF Err]SpicNVMCalStore: The flash memory(@0x9080 = 0x1210000) is not able to be write, Erase it first!!
===== Enter Image 1 ====
SPI calibration
Find the avaiable window
Baud:2; auto_length:21; Delay start:0; Delay end:63
[SPIF Err]SpicNVMCalStore: The flash memory(@0x90b0 = 0x202102) is not able to be write, Erase it first!!
SDR Controller Init
Test 0: No match addr 0xc9d38 => 0xf != 0xc
Test 0: No match addr 0x1f7c10 => 0x5 != 0xa

Default Im2 INVALID

OTA Im INVALID

Fatal:no fw

```

but with the ramdebug everything is ok...

**Comment by parasite85** [comment]
@Mantikor 
Great progress.
Currently I cannot dedicate time for Tuya activity (I`m busy in next couple weeks). 
If you will find something wrong / something worth to mention in repo, feel free to contribute.
If you stuck at something, I`ll try to help you.

**Comment by codeandsolder** [comment]
What fixed the "Default Im2 INVALID" problem for me is commenting out line 662 in application.mk (`$(STRIP) $(BIN_DIR)/$(TARGET).axf`)
